# Generated by Django 5.2.1 on 2025-05-30 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Category'},
        ),
    ]
