# Generated by Django 5.2.1 on 2025-05-30 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'category'},
        ),
    ]
